POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "John Doe",
    "number": "123-345678"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jane Doe"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Neo",
    "number": 12345678
}