POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "John Doe",
    "number": "1234"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jane Doe"
}